Add ckecks of PR

diff --git a/.github/workflows/5_bumper_repository.yml b/.github/workflows/5_bumper_repository.yml
--- a/.github/workflows/5_bumper_repository.yml
+++ b/.github/workflows/5_bumper_repository.yml
@@ -141,6 +141,11 @@ jobs:
             --body "Issue: ${{ inputs.issue-link }}" \
             --base ${{ github.ref_name }} \
             --head ${{ steps.vars.outputs.branch_name }})
+          
+          if [[ -z "$PR_URL" ]]; then
+             echo "Error: PR was not created."
+             exit 1
+          fi
 
           echo "Pull request created: ${PR_URL}"
           echo "pull_request_url=${PR_URL}" >> $GITHUB_OUTPUT
@@ -149,7 +154,12 @@ jobs:
         if: steps.check_changes.outputs.has_changes == 'true'
         run: |
           # Any checks for the PR are bypassed since the branch is expected to be functional (i.e. the bump process does not introduce any bugs)
-          gh pr merge "${{ steps.create_pr.outputs.pull_request_url }}" --squash --admin
+          PR_URL="${{ steps.create_pr.outputs.pull_request_url }}"
+          if [[ -z "$PR_URL" ]]; then
+              echo "Error: No PR URL available. Cannot merge."
+              exit 1
+          fi
+          gh pr merge "$PR_URL" --squash --admin
 
       - name: Show logs
         run: |
